name: n8n-tesseract

services:
  n8n:
    build:
      dockerfile: ./Dockerfile
    ports:
      - 5678
    env:
      N8N_BASIC_AUTH_ACTIVE: true
      N8N_BASIC_AUTH_USER: admin
      N8N_BASIC_AUTH_PASSWORD: admin123
      N8N_HOST: 0.0.0.0
      N8N_PORT: 5678
      N8N_PROTOCOL: http
      WEBHOOK_TUNNEL_URL: https://n8n-private.kretyastudio.com/
    domains:
      - https://n8n-private.kretyastudio.com/
